spring:
  liquibase:
    enabled: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
myProperty: myTestProperty
testconfig:
  my-property2: dsa
  my-property1: asd


logging:
  level:
    org.zalando.logbook: TRACE
logbook:
  format:
    style: http
